### ISSUE TITLE
Feedback for /mapbox-gl-js/example/mapbox-gl-geocoder-outside-the-map/

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mapbox-gl-js-docs#8] opened 2019-08-05 18:29 UTC
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/mapbox-gl-js/example/mapbox-gl-geocoder-outside-the-map/](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-outside-the-map/)
* Section: null
* Date received: 2019-08-03T23:20:43.520Z
* Was this page helpful?: 😕

Feedback:
> how is this 'outside the map' it still shows inside/on the map - outsode would be above, below, left or right! This example is really confusing

Similar: https://github.com/mapbox/mapbox-gl-js/issues/7877

**Comment by andrewharvey** [comment] 2019-08-14 02:15
Agreed this is exactly https://github.com/mapbox/mapbox-gl-js/issues/7877.

**Comment by andrewharvey** [comment] 2019-08-15 10:20
I'll close this as a duplicate of #39 (if that's wrong, please just re-open!).

**Closed by andrewharvey** 2019-08-15 10:20 UTC
Labels: customer-feedback, ❓needs to be addressed, 🏷 improvement
